name: CI
on:
  push:
    branches:
      - main
      - master
      - '*v'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby-version }}'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3']
        allow-failure: [false]
        frozen-string: [false]
        include:
          - ruby-version: '3.2'
            allow-failure: true
            frozen-string: true
          - ruby-version: '3.1'
            allow-failure: true
            frozen-string: true
          - ruby-version: '3.0'
            allow-failure: true
            frozen-string: true
          - ruby-version: '2.7'
            allow-failure: false
            frozen-string: true
          - ruby-version: '2.6'
            allow-failure: false
            frozen-string: true
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      - name: Install bundler
        run: |
          gem update --system 3.2.3
          gem install bundler
          bundle install

      - run: echo "{RUBYOPT}={--enable-frozen-string-literal}" >> $GITHUB_ENV
        if: ${{ matrix.frozen-string }}
      - run: bin/rake
